pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html app.slim.js app.css obq_index.json public/
    - cp -r vendor public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
